// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/coin/coin_service.proto

package coin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_coin_coin_service_proto protoreflect.FileDescriptor

const file_api_coin_coin_service_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/coin/coin_service.proto\x120github.unless24.coin.server.protobuf.api.coin.v1\x1a\x17api/coin/messages.proto2\xb8\x02\n" +
	"\vCoinService\x12\x94\x01\n" +
	"\tListCoins\x12B.github.unless24.coin.server.protobuf.api.coin.v1.ListCoinsRequest\x1aC.github.unless24.coin.server.protobuf.api.coin.v1.ListCoinsResponse\x12\x91\x01\n" +
	"\bGetQuote\x12A.github.unless24.coin.server.protobuf.api.coin.v1.GetQuoteRequest\x1aB.github.unless24.coin.server.protobuf.api.coin.v1.GetQuoteResponseB\xc1\x02\n" +
	"4com.github.unless24.coin.server.protobuf.api.coin.v1B\x10CoinServiceProtoP\x01Z\fpkg/api/coin\xa2\x02\aGUCSPAC\xaa\x020Github.Unless24.Coin.Server.Protobuf.Api.Coin.V1\xca\x020Github\\Unless24\\Coin\\Server\\Protobuf\\Api\\Coin\\V1\xe2\x02<Github\\Unless24\\Coin\\Server\\Protobuf\\Api\\Coin\\V1\\GPBMetadata\xea\x027Github::Unless24::Coin::Server::Protobuf::Api::Coin::V1b\x06proto3"

var file_api_coin_coin_service_proto_goTypes = []any{
	(*ListCoinsRequest)(nil),  // 0: github.unless24.coin.server.protobuf.api.coin.v1.ListCoinsRequest
	(*GetQuoteRequest)(nil),   // 1: github.unless24.coin.server.protobuf.api.coin.v1.GetQuoteRequest
	(*ListCoinsResponse)(nil), // 2: github.unless24.coin.server.protobuf.api.coin.v1.ListCoinsResponse
	(*GetQuoteResponse)(nil),  // 3: github.unless24.coin.server.protobuf.api.coin.v1.GetQuoteResponse
}
var file_api_coin_coin_service_proto_depIdxs = []int32{
	0, // 0: github.unless24.coin.server.protobuf.api.coin.v1.CoinService.ListCoins:input_type -> github.unless24.coin.server.protobuf.api.coin.v1.ListCoinsRequest
	1, // 1: github.unless24.coin.server.protobuf.api.coin.v1.CoinService.GetQuote:input_type -> github.unless24.coin.server.protobuf.api.coin.v1.GetQuoteRequest
	2, // 2: github.unless24.coin.server.protobuf.api.coin.v1.CoinService.ListCoins:output_type -> github.unless24.coin.server.protobuf.api.coin.v1.ListCoinsResponse
	3, // 3: github.unless24.coin.server.protobuf.api.coin.v1.CoinService.GetQuote:output_type -> github.unless24.coin.server.protobuf.api.coin.v1.GetQuoteResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_coin_coin_service_proto_init() }
func file_api_coin_coin_service_proto_init() {
	if File_api_coin_coin_service_proto != nil {
		return
	}
	file_api_coin_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_coin_coin_service_proto_rawDesc), len(file_api_coin_coin_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_coin_coin_service_proto_goTypes,
		DependencyIndexes: file_api_coin_coin_service_proto_depIdxs,
	}.Build()
	File_api_coin_coin_service_proto = out.File
	file_api_coin_coin_service_proto_goTypes = nil
	file_api_coin_coin_service_proto_depIdxs = nil
}
